### ISSUE TITLE
Convert and redesign do FS25

### ISSUE THREAD

**Issue by Achimobil** [Achimobil/FS25_MapObjectsHider#1]
Convert and redesign do FS25

**Comment by Achimobil** [comment]
Einigen Fortschritt gemacht, so dass der Hider im SP jetzt schon funktonieren sollte. 
Fehlt noch das syncen im MP beim connecten und dann sollte alles für MP testbar sein

**Comment by Trivium1709** [comment]
Do you have an ETA for the release? Also, if you need a tester let me know! Thanks for committing to the conversion of this mod!

**Comment by Achimobil** [comment]
Nope, there will be no ETA. Only the fact that I am working on it. 
And testing can done by everyone which is able to build a md from the github ;)

**Comment by Trivium1709** [comment]
> Nope, there will be no ETA. Only the fact that I am working on it. And testing can done by everyone which is able to build a md from the github ;)

Yeah I just saw your video on how to do it, so far its working fine, thanks :)

**Comment by Achimobil** [comment]
Ready and testet in SP. Needs to be tested in MP as next

**Comment by SomethingLikeAChicken** [comment]
@Achimobil Weist du wie man den Mod auf einem Nitrado server installieren kann? Wollte mal testen wies im MP aussieht.

**Comment by Achimobil** [comment]
Wie jeder andere mod auch, verpacken und hoch laden

**Comment by Achimobil** [comment]
Tests abgeschlossen, funktioniert bei mir wunderbar, wird dann jetzt in modhub eingereicht
