### ISSUE TITLE
Wasserpumpe Reisfeld - Ausblenden bewirkt Aufhängen des FS beim Spielstand laden

### ISSUE THREAD

**Issue by haamic** [Achimobil/FS25_MapObjectsHider#2]
Guten Abend Achim,
ich habe am Reisfeld, bei der Wasserpumpe die Kollision ausgeblendet. (auch beim kompletten Ausblenden getestet, gleiches Problem)
Soweit im Spiel klappt  das Ausblenden wunderbar, aber nach speichern und laden des Spielstandes, lädt die Karte dann nicht mehr.
In der mapObjectsHider.xml wird für die Pumpe ein Eintrag erzeugt, worin ein **leerer Index** steht. 
Daran scheint sich der FS aufzuhängen. Das liegt vermutlich an der Besonderheit der Wasserpumpe. 
Sie ist wohl kein normales mapObject, sondern gehört zum Reisfeld.
Vielleicht gibts dazu mal eine Lösung, ansonsten kann ich damit leben, das der normale Helfer und/oder Courseplay da dran hängen bleiben. 
Hier der  Eintrag:
```
<object name="visual_lod" index="" date="22/12/2024" time="17:29:34" player="X" onlyDecollide="false" timestamp="192216574" hash="e1b9a099e066c1c1db667e6dd1e8bb09">
<collision name="col" index="" rigidBodyType="1"/>
</object>
```
Schönen Abend
Gruss Micha

**Comment by Achimobil** [comment]
Schau ich mir auf jeden fall an
