### ISSUE TITLE
nur Kollision entfernen bei Bäumen? Ging das nicht mal?

### ISSUE THREAD

**Issue by haamic** [Achimobil/FS25_MapObjectsHider#4]
Hallo Achim,
Ging das nicht mal, das bei Bäumen auch nur die Kollision entfernt werden konnte, oder bilde ich mir das nur ein?
Evtl. hat sich seit dem neuen Update (durch mein Issue wegen der Wasserpumpe am Reisfeld) ein Fehler eingeschlichen, oder ist das so gewollt??
Wenn ich die Taste für "nur Kollision entfernen" drücke verschwindet der komplette Baum.
z.b. ein Baum, der einem Fahrzeug bisschen im Weg steht, verschwindet nun ganz, obwohl eigentlich nur die Kollision entfernt werden sollte.
Bei Strommasten, gehts ja wie gewünscht.
Wenns noch nie ging, dann kann hier geschlossen werden. Ansonsten bitte bei Gelegenheit mal nachschauen und möglicherweise reaktivieren.
Dankeschön. 
Gruss Micha

**Comment by Achimobil** [comment]
Nein, das ging noch nie. Bäume sind keine richtigen Objekte sondern nur Split types.
